# Generated by Django 3.2.12 on 2023-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthese', '0002_auto_20230719_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheseavis',
            name='statut',
            field=models.IntegerField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0),
        ),
    ]
