# Generated by Django 4.2 on 2023-05-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0001_initial'),
        ('collaborateurs', '0002_alter_collaborateurs_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adresse.adress'),
        ),
    ]
