# Generated by Django 4.2 on 2023-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0003_alter_collaborateurs_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
