# Generated by Django 3.2.19 on 2023-06-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RICT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisarticle',
            name='rict',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RICT.rict'),
            preserve_default=False,
        ),
    ]
