# Generated by Django 3.2.19 on 2023-06-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_alter_mission_mission_parent'),
        ('RICT', '0002_avisarticle_rict'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mission.article'),
            preserve_default=False,
        ),
    ]
