# Generated by Django 3.2.19 on 2023-06-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RICT', '0003_disposition_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposition',
            name='type',
        ),
    ]
