# Generated by Django 3.2.19 on 2023-06-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RICT', '0005_disposition_unique_rict_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisarticle',
            name='collaborateurs',
        ),
    ]
