# Generated by Django 3.2.19 on 2023-06-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RICT', '0006_remove_avisarticle_collaborateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionSommaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict')),
            ],
        ),
    ]
