# Generated by Django 3.2.12 on 2023-07-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RICT', '0008_commentaireavisarticle_synthese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaireavisarticle',
            name='synthese',
        ),
    ]
