# Generated by Django 3.2.12 on 2023-09-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0012_alter_articlemission_mission'),
        ('RICT', '0012_auto_20230821_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.missionactive')),
                ('rict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict')),
            ],
        ),
    ]
