# Generated by Django 3.2.12 on 2023-10-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0038_auto_20230721_1502'),
        ('RICT', '0013_missionrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.documents')),
                ('rict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict')),
            ],
        ),
    ]
