#!/usr/bin/bash
pkill python3
python3 ./aleatek/manage.py seed adresse
python3 ./aleatek/manage.py seed collaborateurs
python3 ./aleatek/manage.py seed entreprise
python3 ./aleatek/manage.py seed Dashbord
