#!/usr/bin/bash
pkill python3
python ./aleatek/manage.py seed adresse
python ./aleatek/manage.py seed collaborateurs
python ./aleatek/manage.py seed entreprise
python ./aleatek/manage.py seed Dashbord
