#!/usr/bin/bash
pkill python3

rm ./aleatek/db.sqlite3
python3 ./aleatek/manage.py makemigrations
python3 ./aleatek/manage.py migrate
python3 ./aleatek/manage.py createsuperuser
python3 ./aleatek/manage.py runserver