# Generated by Django 4.2 on 2023-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cplt_geo', models.CharField(max_length=250)),
                ('numero_voie', models.CharField(max_length=500)),
                ('lieu_dit', models.CharField(max_length=250)),
                ('compte_postal', models.CharField(blank=True, max_length=5)),
                ('ville', models.CharField(max_length=500)),
                ('pays', models.CharField(default='France', max_length=500)),
                ('departement', models.CharField(default='Mompellier', max_length=500)),
                ('province', models.CharField(max_length=500)),
            ],
        ),
    ]
