# Generated by Django 3.2.19 on 2023-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='compte_postal',
            new_name='code_postal',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='province',
        ),
        migrations.AlterField(
            model_name='adress',
            name='cplt_geo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='adress',
            name='lieu_dit',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='adress',
            name='numero_voie',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='adress',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=500),
        ),
        migrations.AlterField(
            model_name='adress',
            name='ville',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
