# Generated by Django 4.2 on 2023-05-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentaire', '0001_initial'),
        ('ouvrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='id_avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.avis'),
        ),
    ]
