# Generated by Django 3.2.12 on 2023-08-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0004_remove_commentaire_synthese'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='lever',
            field=models.BooleanField(default=False),
        ),
    ]
