# Generated by Django 4.2 on 2023-05-31 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashbord', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffaireOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (4, 'diffusé')], max_length=10)),
                ('id_affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(choices=[('Execution', 'Execution'), ('Conception', 'Conception')], default='Execution', max_length=200)),
                ('nature', models.CharField(choices=[('TOUS', 'TOUS'), ('Descriptif', 'Descriptif'), ('AT/DTA', 'AT/DTA'), ('Attestation Incendie', 'Attestation Incendie'), ('Carnet', 'Carnet'), ('Certificat', 'Certificat'), ('Certificat incendie', 'Certificat incendie'), ('Compte rendue', 'Compte rendu'), ('Courrier', 'Courrier'), ('fiche techinique', 'Fiche Technique'), ('Note', 'Note'), ('Note de calcule', 'Note de calcule'), ('Notice', 'Notice'), ('Plan', 'Plan'), ('PV', 'PV'), ('PV Incendie', 'PV Incendie'), ('Rapport', 'Rapport'), ('Schéma', 'Schéma')], max_length=30)),
                ('indice', models.IntegerField()),
                ('date_indice', models.DateField()),
                ('date_reception', models.DateField()),
                ('titre', models.CharField(max_length=100)),
                ('numero_revision', models.IntegerField()),
                ('affaireouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.affaireouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FichierAttache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritaire', models.BooleanField(default=False)),
                ('nom_fichier', models.CharField(max_length=250)),
                ('fichier', models.FileField(upload_to='fichierattachedocument')),
                ('cree_le', models.DateField()),
                ('action', models.BooleanField(default=False)),
                ('document_attache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codification', models.CharField(choices=[('F', 'F'), ('RMQ', 'RMQ'), ('FA', 'FA'), ('HM', 'HM'), ('SO', 'SO'), ('VI', 'VI')], max_length=23)),
                ('constructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affaireouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.affaireouvrage')),
                ('redacteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='affaireouvrage',
            name='id_ouvrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.ouvrage'),
        ),
        migrations.AddField(
            model_name='affaireouvrage',
            name='validateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
