# Generated by Django 4.2 on 2023-06-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0015_remove_planaffaire_reunions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ouvrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
