# Generated by Django 4.2 on 2023-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0002_rapportvisite'),
        ('ouvrage', '0003_alter_affaireouvrage_statut_and_more'),
    ]

    operations = [
    ]
