# Generated by Django 4.2 on 2023-06-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0004_merge_20230602_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='affaireouvrage',
        ),
        migrations.AddField(
            model_name='documents',
            name='emetteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ouvrage.entrepriseaffaireouvrage'),
        ),
    ]
