# Generated by Django 4.2 on 2023-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0005_remove_documents_affaireouvrage_documents_emetteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichierattache',
            old_name='cree_le',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fichierattache',
            old_name='document_attache',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='fichierattache',
            old_name='nom_fichier',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='fichierattache',
            name='action',
        ),
        migrations.RemoveField(
            model_name='fichierattache',
            name='prioritaire',
        ),
        migrations.AddField(
            model_name='documents',
            name='numero_externe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='indice',
            field=models.CharField(max_length=5),
        ),
    ]
