# Generated by Django 4.2 on 2023-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0009_alter_aso_redacteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso',
            name='date',
            field=models.DateField(default='2000-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aso',
            name='statut',
            field=models.CharField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0, max_length=10),
        ),
    ]
