# Generated by Django 4.2 on 2023-06-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0010_aso_date_aso_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RapportVisite',
        ),
    ]
