# Generated by Django 4.2 on 2023-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0011_delete_rapportvisite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrepriseaffaireouvrage',
            constraint=models.UniqueConstraint(fields=('affaire_ouvrage', 'affaire_entreprise'), name='unique_entreprise_ouvrage'),
        ),
    ]
