# Generated by Django 4.2 on 2023-06-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0014_documents_traite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaireouvrage',
            name='statut',
        ),
    ]
