# Generated by Django 4.2 on 2023-06-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0015_remove_affaireouvrage_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='traite',
        ),
        migrations.AddField(
            model_name='documents',
            name='aso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ouvrage.aso'),
        ),
    ]
