# Generated by Django 4.2 on 2023-06-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0016_remove_documents_traite_documents_aso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaireouvrage',
            name='diffusion',
        ),
    ]
