# Generated by Django 3.2.19 on 2023-06-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0017_remove_affaireouvrage_diffusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_indice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.entrepriseaffaireouvrage'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='indice',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='numero_revision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
