# Generated by Django 3.2.19 on 2023-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0018_auto_20230617_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='valider',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
