# Generated by Django 3.2.19 on 2023-06-17 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ouvrage', '0019_documents_valider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaireouvrage',
            name='validateur',
        ),
        migrations.AddField(
            model_name='documents',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
