# Generated by Django 3.2.19 on 2023-06-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0020_auto_20230617_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='valider',
        ),
    ]
