# Generated by Django 3.2.19 on 2023-06-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0026_auto_20230621_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='titre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
