# Generated by Django 3.2.19 on 2023-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0027_alter_documents_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso',
            name='order_in_affaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='documentaffectation',
            constraint=models.UniqueConstraint(fields=('document', 'collaborateur'), name='unique_document_affectation'),
        ),
    ]
