# Generated by Django 3.2.19 on 2023-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0028_auto_20230621_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='order_in_affaire',
            field=models.IntegerField(),
        ),
    ]
