# Generated by Django 3.2.12 on 2023-07-01 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ouvrage', '0029_alter_aso_order_in_affaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='numero_revision',
        ),
        migrations.AddField(
            model_name='documents',
            name='editeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrageDocumentsediteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
