# Generated by Django 3.2.12 on 2023-07-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0030_auto_20230701_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='editeur',
        ),
    ]
