# Generated by Django 3.2.12 on 2023-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0031_remove_documents_editeur'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='affaireouvrage',
            constraint=models.UniqueConstraint(fields=('id_affaire', 'id_ouvrage'), name='unique_affaire_document'),
        ),
    ]
