# Generated by Django 3.2.12 on 2023-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0032_affaireouvrage_unique_affaire_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaireouvrage',
            name='diffusion',
            field=models.BooleanField(default=False),
        ),
    ]
