# Generated by Django 3.2.12 on 2023-07-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0033_affaireouvrage_diffusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
