# Generated by Django 3.2.12 on 2023-07-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0034_documents_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('id_document', 'collaborateurs'), name='unique_avis_collaborateur'),
        ),
    ]
