# Generated by Django 3.2.12 on 2023-07-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0036_remarqueaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarqueaso',
            name='aso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ouvrage.aso'),
            preserve_default=False,
        ),
    ]
