# Generated by Django 4.2 on 2023-05-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        ('adresse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('libelle', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Encours', 'Encours'), ('Achevé', 'Achevé'), ('Abandonné', 'Abandonné')], max_length=20)),
                ('numero_offre', models.IntegerField()),
                ('libelle_contrat', models.CharField(max_length=100)),
                ('date_contrat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('risque', models.CharField(choices=[('Normal', 'Normal'), ('Particulier', 'Particulier'), ('Complexe', 'Complexe')], max_length=20)),
                ('devise', models.CharField(choices=[('$', '$'), ('€', '€')], max_length=10)),
                ('type', models.CharField(choices=[('CTC', 'CTC'), ('VT', 'VT')], max_length=10)),
                ('prix', models.IntegerField()),
                ('debut_chantier', models.DateField()),
                ('fin_chantier', models.DateField()),
                ('reunions', models.IntegerField()),
                ('visite', models.IntegerField()),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adresse.adress')),
                ('batiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.batiment')),
                ('plan_affaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.planaffaire')),
            ],
        ),
    ]
