# Generated by Django 4.2 on 2023-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0003_remove_planaffaire_entreprise_affaire_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaffaire',
            name='libelle',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
