# Generated by Django 4.2 on 2023-06-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_rename_responsable_responsable_entreprise'),
        ('Dashbord', '0005_rename_entreprise_affaire_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
    ]
