# Generated by Django 4.2 on 2023-06-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashbord', '0006_alter_affaire_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='assistant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffaireassistant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affaire',
            name='charge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairecharge', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affaire',
            name='chef',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairechef', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
