# Generated by Django 4.2 on 2023-06-01 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashbord', '0007_affaire_assistant_affaire_charge_affaire_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffaireassistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairecharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairechef', to=settings.AUTH_USER_MODEL),
        ),
    ]
