# Generated by Django 4.2 on 2023-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0008_alter_affaire_assistant_alter_affaire_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaffaire',
            name='type_montant',
            field=models.CharField(choices=[('HT', 'HT'), ('TTC', 'TTC')], default='HT', max_length=10),
        ),
    ]
