# Generated by Django 4.2 on 2023-06-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0011_planaffaire_debut_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.batiment'),
        ),
    ]
