# Generated by Django 4.2 on 2023-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0012_alter_chantier_batiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='libelle_contrat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
