# Generated by Django 4.2 on 2023-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0013_alter_affaire_libelle_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='libelle_contrat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
