# Generated by Django 4.2 on 2023-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0014_alter_affaire_libelle_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaffaire',
            name='reunions',
        ),
    ]
