# Generated by Django 4.2 on 2023-06-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_rename_responsable_responsable_entreprise'),
        ('Dashbord', '0017_alter_entrepriseaffaire_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepriseaffaire',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
    ]
