# Generated by Django 4.2 on 2023-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0018_alter_entrepriseaffaire_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='libelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
