# Generated by Django 4.2 on 2023-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0019_alter_planaffaire_libelle'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrepriseaffaire',
            constraint=models.UniqueConstraint(fields=('entreprise', 'affaire'), name='unique_entreprise_affaire'),
        ),
    ]
