# Generated by Django 3.2.19 on 2023-06-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0020_entrepriseaffaire_unique_entreprise_affaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='numero',
        ),
    ]
