# Generated by Django 3.2.19 on 2023-06-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashbord', '0021_remove_affaire_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffaireassistant', to='collaborateurs.collaborateurs'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairecharge', to='collaborateurs.collaborateurs'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DashbordAffairechef', to='collaborateurs.collaborateurs'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='date_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='numero_offre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
