# Generated by Django 3.2.19 on 2023-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0022_auto_20230616_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='debut_chantier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='debut_prestation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='fin_chantier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='visite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
