# Generated by Django 3.2.19 on 2023-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0023_auto_20230616_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='numero_contrat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
