# Generated by Django 3.2.19 on 2023-06-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprise', '0006_auto_20230616_1349'),
        ('Dashbord', '0026_auto_20230618_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DashbordAffaireassistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DashbordAffairecharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DashbordAffairechef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise'),
        ),
    ]
