# Generated by Django 3.2.12 on 2023-07-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0027_auto_20230621_0044'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entrepriseaffaire',
            name='unique_entreprise_affaire',
        ),
    ]
