# Generated by Django 3.2.12 on 2023-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0029_entrepriseaffaire_unique_entreprise_affaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='etendu',
            field=models.TextField(default=''),
        ),
    ]
