# Generated by Django 3.2.12 on 2023-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0030_affaire_etendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='numero_contrat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
