# Generated by Django 4.2 on 2023-05-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashbord', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_mission', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MissionActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
                ('id_mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mission.mission')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_collaborateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_mission_active', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mission.missionactive')),
            ],
        ),
    ]
