# Generated by Django 4.2 on 2023-06-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0015_remove_planaffaire_reunions'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionactive',
            name='id_affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire'),
        ),
        migrations.AlterField(
            model_name='missionactive',
            name='id_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission'),
        ),
    ]
