# Generated by Django 4.2 on 2023-06-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0002_alter_missionactive_id_affaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontechnique',
            name='affecteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ITAffecteur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interventiontechnique',
            name='date',
            field=models.DateField(default='2000-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='id_collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ITAffecter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='id_mission_active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.missionactive'),
        ),
    ]
