# Generated by Django 3.2.19 on 2023-06-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_auto_20230618_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'mission_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_missions', to='mission.mission'),
        ),
    ]
