# Generated by Django 3.2.19 on 2023-07-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_alter_mission_mission_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.article')),
                ('id_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission')),
            ],
        ),
    ]
