# Generated by Django 3.2.12 on 2023-07-02 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_alter_article_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventiontechnique',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='interventiontechnique',
            constraint=models.UniqueConstraint(fields=('id_mission_active', 'id_collaborateur'), name='unique_IT'),
        ),
    ]
