# Generated by Django 3.2.12 on 2023-08-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0008_auto_20230702_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mission',
        ),
        migrations.CreateModel(
            name='ArticleMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='mission.article')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.mission')),
            ],
        ),
        migrations.AlterField(
            model_name='articleselect',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_article_select', to='mission.articlemission'),
        ),
    ]
