# Generated by Django 3.2.12 on 2023-08-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0009_auto_20230814_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
