# Generated by Django 3.2.12 on 2023-08-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0010_alter_article_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleselect',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_article_select', to='mission.article'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('titre',), name='unique_titre'),
        ),
        migrations.AddConstraint(
            model_name='articlemission',
            constraint=models.UniqueConstraint(fields=('article', 'mission'), name='unique_article_mission'),
        ),
        migrations.AddConstraint(
            model_name='articleselect',
            constraint=models.UniqueConstraint(fields=('article', 'affaire'), name='unique_affaire_article'),
        ),
    ]
