# Generated by Django 3.2.12 on 2023-08-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0011_auto_20230820_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemission',
            name='mission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='mission.mission'),
            preserve_default=False,
        ),
    ]
