# Generated by Django 3.2.12 on 2023-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0012_alter_articlemission_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='code_mission',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
