# Generated by Django 3.2.12 on 2023-10-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0013_alter_mission_code_mission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='unique_titre',
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('titre', 'article_parent'), name='unique_titre'),
        ),
    ]
