# Generated by Django 4.2 on 2023-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_remove_entreprise_raison_sociale_entreprise_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='nom',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='raison_sociale',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
