# Generated by Django 4.2 on 2023-05-31 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_remove_entreprise_nom_entreprise_raison_sociale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsable',
            old_name='responsable',
            new_name='entreprise',
        ),
    ]
