# Generated by Django 3.2.19 on 2023-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_rename_responsable_responsable_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='activite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='siret',
            field=models.IntegerField(blank=True),
        ),
    ]
