# Generated by Django 3.2.19 on 2023-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_auto_20230616_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='activite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='siret',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
