# Generated by Django 4.2 on 2023-06-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0011_delete_rapportvisite'),
        ('rapport_visite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.affaireouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireAvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.avisouvrage')),
            ],
        ),
    ]
