# Generated by Django 3.2.19 on 2023-06-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ouvrage', '0017_remove_affaireouvrage_diffusion'),
        ('rapport_visite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.affaireouvrage')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rapportvisite',
            name='redacteur',
        ),
        migrations.AddField(
            model_name='rapportvisite',
            name='statut',
            field=models.CharField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='CommentaireAvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.avisouvrage')),
            ],
        ),
        migrations.AddField(
            model_name='avisouvrage',
            name='rv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.rapportvisite'),
        ),
    ]
