# Generated by Django 3.2.19 on 2023-06-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_visite', '0003_alter_commentaireavisouvrage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportvisite',
            name='objet',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
