# Generated by Django 3.2.19 on 2023-06-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_visite', '0004_alter_rapportvisite_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisouvrage',
            name='objet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commentaireavisouvrage',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
