# Generated by Django 3.2.19 on 2023-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_visite', '0006_alter_rapportvisite_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportvisite',
            name='order_in_affaire',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
