# Generated by Django 3.2.19 on 2023-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_visite', '0007_rapportvisite_order_in_affaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaireavisouvrage',
            name='asuivre',
            field=models.BooleanField(default=False),
        ),
    ]
